### PR TITLE
auto-firmware copy & script flags for CI

### PR DESCRIPTION
**Pull request by ctcDNightmare**
Small enhancement to watch the exit-code of the buildscript and move the generated firmware out of the marlin folder into a build directory including build-date and targetboard.

Also added -s/-f to force or skip marlin updates to use the script in a CI environment more easily.

### CODE REVIEW

**Review by frealmyr — APPROVED** [review]
Neat!

**Comment by frealmyr** [comment]
Removed `CustomConfiguration/` in `.gitignore` as i will make the repo more generic in a future commit.

**Comment by ctcDNightmare** [comment]
Mind marking it as hacktoberfest-accepted again? :)

**Comment by frealmyr** [comment]
> Mind marking it as hacktoberfest-accepted again? :)

Sure thing!

**Pull request merged**
